"""MemoClaw Python SDK — semantic memory for AI agents."""

__version__ = "0.1.0"

from .builders import MemoryBuilder, RecallBuilder
from .client import AsyncMemoClaw, MemoClaw
from .errors import (
    APIError,
    AuthenticationError,
    ForbiddenError,
    InternalServerError,
    MemoClawError,
    NotFoundError,
    PaymentRequiredError,
    RateLimitError,
    ValidationError,
)
from .config import MemoClawConfig, load_config
from .types import (
    ClusterInfo,
    ContextResult,
    ExportResponse,
    HistoryEntry,
    HistoryResponse,
    Namespace,
    NamespaceCount,
    NamespacesResponse,
    RelatedMemorySummary,
    ConsolidateResult,
    DeleteResult,
    ExtractResult,
    FreeTierStatus,
    IngestResult,
    ListResponse,
    Memory,
    MemoryType,
    MigrateResult,
    Message,
    RecallMemory,
    RecallResponse,
    RecallSignals,
    Relation,
    RelationsResponse,
    RelationType,
    RelationWithMemory,
    StatsResponse,
    StoreBatchResult,
    StoreInput,
    StoreResult,
    SuggestedCategory,
    SuggestedMemory,
    SuggestedResponse,
    TypeCount,
    CoreMemoriesResponse,
    TextSearchResponse,
    UpdateBatchResult,
    UpdateInput,
)
from .builders import (
    AsyncMemoryFilter,
    AsyncRecallQuery,
    AsyncStoreBuilder,
    BatchStore,
    MemoryFilter,
    RecallQuery,
    RelationBuilder,
    StoreBuilder,
)

__all__ = [
    "__version__",
    # Clients
    "MemoClaw",
    "AsyncMemoClaw",
    # Builders
    "MemoryBuilder",
    "RecallBuilder",
    # Errors
    "MemoClawError",
    "APIError",
    "AuthenticationError",
    "PaymentRequiredError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "RateLimitError",
    "InternalServerError",
    # Types
    "Memory",
    "MemoryType",
    "Message",
    "RecallMemory",
    "RecallResponse",
    "RecallSignals",
    "Relation",
    "RelatedMemorySummary",
    "RelationsResponse",
    "RelationType",
    "RelationWithMemory",
    "StoreResult",
    "StoreBatchResult",
    "StoreInput",
    "ListResponse",
    "DeleteResult",
    "IngestResult",
    "ExtractResult",
    "ConsolidateResult",
    "ClusterInfo",
    "SuggestedMemory",
    "SuggestedResponse",
    "SuggestedCategory",
    "FreeTierStatus",
    "MigrateResult",
    "ContextResult",
    "Namespace",
    "NamespacesResponse",
    "NamespaceCount",
    "StatsResponse",
    "TypeCount",
    "ExportResponse",
    "HistoryEntry",
    "HistoryResponse",
    "UpdateInput",
    "UpdateBatchResult",
    "CoreMemoriesResponse",
    "TextSearchResponse",
    "MemoClawConfig",
    "load_config",
    # Builders
    "RecallQuery",
    "AsyncRecallQuery",
    "MemoryFilter",
    "AsyncMemoryFilter",
    "RelationBuilder",
    "BatchStore",
    "StoreBuilder",
    "AsyncStoreBuilder",
]
